# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurgeProyect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer', models.CharField(max_length=30, unique=True)),
                ('server', models.CharField(max_length=30)),
                ('protocolo', models.CharField(max_length=10)),
                ('purge_method', models.CharField(max_length=10)),
                ('delta_time', models.PositiveSmallIntegerField(default=0)),
                ('generate_new_cache', models.BooleanField()),
                ('exclude_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['referer'],
                'verbose_name': 'Purge Proyect',
                'verbose_name_plural': 'Purge Proyects',
            },
        ),
        migrations.CreateModel(
            name='ToPurge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='created at')),
                ('total_asked', models.IntegerField(default=0)),
                ('total_purged', models.IntegerField(default=0)),
                ('next_ask', models.IntegerField(default=0)),
                ('future_ask', models.IntegerField(default=0)),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purge.PurgeProyect')),
            ],
            options={
                'ordering': ['proyect', 'url'],
                'verbose_name': 'URL to Purge',
                'verbose_name_plural': 'URLs to Purge',
            },
        ),
        migrations.AlterUniqueTogether(
            name='topurge',
            unique_together=set([('proyect', 'url')]),
        ),
    ]
