# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-14 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topurge',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
