# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-30 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purge', '0002_auto_20180514_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purgeproyect',
            name='generate_new_cache',
        ),
        migrations.AddField(
            model_name='purgeproyect',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Proyect description'),
        ),
        migrations.AlterField(
            model_name='purgeproyect',
            name='protocolo',
            field=models.CharField(default='http://', max_length=10),
        ),
        migrations.AlterField(
            model_name='purgeproyect',
            name='purge_method',
            field=models.CharField(default='/PURGE', max_length=10),
        ),
        migrations.AlterField(
            model_name='purgeproyect',
            name='server',
            field=models.CharField(help_text='Send purges to servers, separate by space', max_length=50),
        ),
    ]
